imported Chris's work - Campus Category for feature 1 Therefore current hierarchy:
Category
         -> Transport
                      -> Bus
                      -> Minibus
         -> Academic
                      -> Staff
         -> Social
                      -> Societies
                      -> Recreation
         -> Function *
                      -> TimeTable
         -> Campus
                      -> CampusETA

Changes:
- added Wagner-Fischer's algorithm to handle user typos (NOTE that it would be used later if have time)
- added Utilities.max(), Utilities.min() functions
- fixed .contains() matching TA vs TimeTable, and TA vs LTA those nasty bugs

Tests:
- added three tests including Chris's and all succeed

Potential Problem:
- NoClassDefFoundError occurred while
      Campus.QUERY_KEYWORD = CampusETA.CAMPUS_DIRECTION_KEYWORD;
  still cannot figure out why